"use client"

import { Github, Linkedin, Twitter, Brain, Heart, Zap } from "lucide-react"

export default function Footer() {
  return (
    <footer className="border-t border-border/50 bg-gradient-to-br from-card/50 to-muted/20 backdrop-blur-sm">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-8">
          {/* Brand */}
          <div>
            <div className="flex items-center gap-3 mb-4">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-primary to-primary/80 flex items-center justify-center shadow-md">
                <Brain className="w-5 h-5 text-primary-foreground" />
              </div>
              <span className="font-bold text-lg bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                chatDAWAH
              </span>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Islamic Q&A chatbot powered by knowledge from Muhammad Ali's "The Muslim Lantern" YouTube channel.
            </p>
            <div className="flex items-center gap-2 mt-4 text-xs text-muted-foreground">
              <Zap className="w-3 h-3 text-primary" />
              <span>Developed by <a href="https://www.mohammaduwaish.com" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline font-medium">Mohammad Uwaish</a></span>
            </div>
          </div>

          {/* About */}
          <div>
            <h4 className="font-semibold text-sm mb-4">About</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="https://www.youtube.com/@themuslimlantern" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary transition-colors">
                  The Muslim Lantern
                </a>
              </li>
              <li>
                <a href="https://www.youtube.com/@themuslimlantern" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary transition-colors">
                  Muhammad Ali
                </a>
              </li>
              <li>
                <a href="https://github.com/mohammaduwaish" target="_blank" rel="noopener noreferrer" className="text-muted-foreground hover:text-primary transition-colors">
                  Developer
                </a>
              </li>
              <li>
                <span className="text-muted-foreground text-xs">
                  Educational Tool
                </span>
              </li>
            </ul>
          </div>

          {/* Data Source */}
          <div>
            <h4 className="font-semibold text-sm mb-4">Data Source</h4>
            <ul className="space-y-2 text-sm">
              <li className="text-muted-foreground text-xs leading-relaxed">
                YouTube transcripts from debates and discussions
              </li>
              <li className="text-muted-foreground text-xs leading-relaxed">
                Topics: Islamic theology, philosophy, interfaith dialogue
              </li>
              <li className="text-muted-foreground text-xs leading-relaxed">
                Channel: The Muslim Lantern
              </li>
            </ul>
          </div>

          {/* Disclaimer */}
          <div>
            <h4 className="font-semibold text-sm mb-4 text-amber-600 dark:text-amber-500">⚠️ Disclaimer</h4>
            <ul className="space-y-2 text-xs text-muted-foreground leading-relaxed">
              <li>
                Muhammad Ali and The Muslim Lantern are NOT responsible for incorrect information generated by this bot.
              </li>
              <li>
                Always verify important religious matters with qualified scholars.
              </li>
              <li>
                For educational purposes only.
              </li>
            </ul>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t border-border/50 pt-8">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
            <div className="flex flex-col items-center sm:items-start gap-2">
              <p className="text-sm text-muted-foreground flex items-center gap-1.5">
                © 2025 chatDAWAH. Made with <Heart className="w-3.5 h-3.5 text-red-500 fill-red-500" /> for the community
              </p>
              <p className="text-xs text-muted-foreground">
                Developed by <a href="https://www.mohammaduwaish.com" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline font-medium">Mohammad Uwaish</a>
              </p>
            </div>
            <div className="flex gap-3">
              <a 
                href="https://www.youtube.com/@themuslimlantern" 
                target="_blank"
                rel="noopener noreferrer"
                className="p-2 rounded-lg text-muted-foreground hover:text-primary hover:bg-primary/10 transition-all duration-200" 
                aria-label="The Muslim Lantern YouTube"
                title="The Muslim Lantern YouTube Channel"
              >
                <svg className="w-4.5 h-4.5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/>
                </svg>
              </a>
              <a 
                href="https://github.com/mohdUwaish59?tab=repositories" 
                target="_blank"
                rel="noopener noreferrer"
                className="p-2 rounded-lg text-muted-foreground hover:text-primary hover:bg-primary/10 transition-all duration-200" 
                aria-label="GitHub"
              >
                <Github className="w-4.5 h-4.5" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}
